---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Imprime la sucesión de números de forma creciente (2, 3, 4) durante la iteración.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Imprime cada número contenido en la lista sin tomar necesariamente un criterio
    de orden.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Imprime la sucesión de números de acuerdo al orden de la lista.
  checked: true
name: Iteración I
